
const places=window.PLACES;const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
let saved=new Set(JSON.parse(localStorage.getItem('creteSaved')||'[]'));
const saveState=()=>localStorage.setItem('creteSaved',JSON.stringify([...saved]));
function img(p){return `<img src="${p.hero}" alt="${p.name}, western Crete" loading="lazy" onerror="this.style.display='none'">`}
function mini(p){return `<article class="mini-card" data-open="${p.id}">${img(p)}<button class="save ${saved.has(p.id)?'saved':''}" data-save="${p.id}" aria-label="Save ${p.name}">${saved.has(p.id)?'♥':'♡'}</button><div class="body"><h3>${p.name}</h3><div class="meta"><span>${p.drive}</span><span>${p.walk} walking</span></div></div></article>`}
function card(p){return `<article class="place-card" data-open="${p.id}">${img(p)}<button class="save ${saved.has(p.id)?'saved':''}" data-save="${p.id}" aria-label="Save ${p.name}">${saved.has(p.id)?'♥':'♡'}</button><div class="body"><p class="eyebrow">${p.area}</p><h3>${p.name}</h3><div class="meta"><span>${p.drive}</span><span>${p.time}</span><span>${p.walk}</span></div><p>${p.summary}</p></div></article>`}
function bindCards(){ $$('[data-open]').forEach(el=>el.onclick=e=>{if(e.target.closest('[data-save]'))return;openPlace(el.dataset.open)});$$('[data-save]').forEach(b=>b.onclick=e=>{e.stopPropagation();saved.has(b.dataset.save)?saved.delete(b.dataset.save):saved.add(b.dataset.save);saveState();renderAll()})}
function renderAll(){ $('#topPicks').innerHTML=['aptera','chania','museum','theriso'].map(id=>mini(places.find(p=>p.id===id))).join('');renderPlaces();renderSaved();bindCards() }
let activeFilter='all';function renderPlaces(){let q=$('#search').value.toLowerCase();let list=places.filter(p=>{let blob=(p.name+' '+p.area+' '+p.summary+' '+p.tags.join(' ')).toLowerCase();let okq=!q||blob.includes(q);let okf=activeFilter==='all'||(activeFilter==='low'?p.energy==='low':p.tags.includes(activeFilter));return okq&&okf});$('#placeGrid').innerHTML=list.map(card).join('')||'<div class="empty" style="display:block"><h3>No matches</h3><p>Try a broader search or another filter.</p></div>';bindCards()}
function renderSaved(){let list=places.filter(p=>saved.has(p.id));$('#savedGrid').innerHTML=list.map(card).join('');$('#emptySaved').style.display=list.length?'none':'block';bindCards()}
function openPlace(id){let p=places.find(x=>x.id===id);$('#dialogContent').innerHTML=`<div class="detail-hero" style="background-image:linear-gradient(0deg,#0008,#0000),url('${p.hero}')"></div><div class="detail"><p class="eyebrow">${p.area}</p><h2>${p.name}</h2><p>${p.summary}</p><div class="facts"><div class="fact"><small>Drive</small><b>${p.drive}</b></div><div class="fact"><small>Time</small><b>${p.time}</b></div><div class="fact"><small>Walking</small><b>${p.walk}</b></div><div class="fact"><small>Cost</small><b>${p.cost}</b></div></div><div class="callout"><h3>Best approach</h3><p>${p.tip}</p></div><div class="callout"><h3>Accessibility note</h3><p>${p.access}</p></div><div class="actions"><a href="${p.maps}" target="_blank" rel="noopener">Directions</a><a href="${p.official}" target="_blank" rel="noopener">Official website</a><a href="${p.trip}" target="_blank" rel="noopener">TripAdvisor</a></div></div>`;$('#placeDialog').showModal()}
$('#closeDialog').onclick=()=>$('#placeDialog').close();$('#placeDialog').onclick=e=>{if(e.target===$('#placeDialog'))$('#placeDialog').close()};
function go(screen){$$('.screen').forEach(s=>s.classList.toggle('active',s.id===screen));$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.screen===screen));scrollTo({top:0,behavior:'smooth'})}
$$('.nav').forEach(n=>n.onclick=()=>go(n.dataset.screen));$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
$('#search').oninput=renderPlaces;$$('.chip').forEach(c=>c.onclick=()=>{$$('.chip').forEach(x=>x.classList.remove('active'));c.classList.add('active');activeFilter=c.dataset.filter;renderPlaces()});
$$('.quick').forEach(q=>q.onclick=()=>{go('explore');let p=q.dataset.preset;activeFilter=p==='spendy'?'boat':p;$$('.chip').forEach(x=>x.classList.toggle('active',x.dataset.filter===activeFilter));renderPlaces()});
$('#suggestBtn').onclick=()=>{let e=$('#energy').value,t=$('#theme').value;let list=places.filter(p=>(e==='any'||p.energy===e)&&(t==='any'||p.tags.includes(t)));list.sort(()=>Math.random()-.5);$('#suggestions').innerHTML=list.slice(0,4).map(mini).join('')||'<p>No exact match. Try “Any” for one option.</p>';bindCards()};
let deferred;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{if(deferred){deferred.prompt();await deferred.userChoice;deferred=null;$('#installBtn').hidden=true}};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
renderAll();
