const places=window.PLACES;const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
let saved=new Set(JSON.parse(localStorage.getItem('creteSaved')||'[]'));
let savedRestaurants=new Set(JSON.parse(localStorage.getItem('creteRestaurantSaved')||'[]'));
const saveState=()=>localStorage.setItem('creteSaved',JSON.stringify([...saved]));
const saveRestaurantState=()=>localStorage.setItem('creteRestaurantSaved',JSON.stringify([...savedRestaurants]));
function img(p){return `<img src="${p.hero}" alt="${p.name}, western Crete" loading="lazy" onerror="this.style.display='none'">`}
function mini(p){return `<article class="mini-card" data-open="${p.id}">${img(p)}<button class="save ${saved.has(p.id)?'saved':''}" data-save="${p.id}" aria-label="Save ${p.name}">${saved.has(p.id)?'♥':'♡'}</button><div class="body"><h3>${p.name}</h3><div class="meta"><span>${p.drive}</span><span>${p.walk} walking</span></div></div></article>`}
function card(p){return `<article class="place-card" data-open="${p.id}">${img(p)}<button class="save ${saved.has(p.id)?'saved':''}" data-save="${p.id}" aria-label="Save ${p.name}">${saved.has(p.id)?'♥':'♡'}</button><div class="body"><p class="eyebrow">${p.area}</p><h3>${p.name}</h3><div class="meta"><span>${p.drive}</span><span>${p.time}</span><span>${p.walk}</span></div><p>${p.summary}</p></div></article>`}
function bindCards(){ $$('[data-open]').forEach(el=>el.onclick=e=>{if(e.target.closest('[data-save]'))return;openPlace(el.dataset.open)});$$('[data-save]').forEach(b=>b.onclick=e=>{e.stopPropagation();saved.has(b.dataset.save)?saved.delete(b.dataset.save):saved.add(b.dataset.save);saveState();renderAll()})}
function renderAll(){ $('#topPicks').innerHTML=['aptera','chania','museum','theriso'].map(id=>mini(places.find(p=>p.id===id))).join('');renderPlaces();renderSaved();bindCards() }
let activeFilter='all';function renderPlaces(){let q=$('#search').value.toLowerCase();let list=places.filter(p=>{let blob=(p.name+' '+p.area+' '+p.summary+' '+p.tags.join(' ')).toLowerCase();let okq=!q||blob.includes(q);let okf=activeFilter==='all'||(activeFilter==='low'?p.energy==='low':p.tags.includes(activeFilter));return okq&&okf});$('#placeGrid').innerHTML=list.map(card).join('')||'<div class="empty" style="display:block"><h3>No matches</h3><p>Try a broader search or another filter.</p></div>';bindCards()}
function renderSaved(){let list=places.filter(p=>saved.has(p.id));$('#savedGrid').innerHTML=list.map(card).join('');$('#emptySaved').style.display=list.length?'none':'block';bindCards();renderSavedRestaurants()}
function openPlace(id){let p=places.find(x=>x.id===id);$('#dialogContent').innerHTML=`<div class="detail-hero" style="background-image:linear-gradient(0deg,#0008,#0000),url('${p.hero}')"></div><div class="detail"><p class="eyebrow">${p.area}</p><h2>${p.name}</h2><p>${p.summary}</p><div class="facts"><div class="fact"><small>Drive</small><b>${p.drive}</b></div><div class="fact"><small>Time</small><b>${p.time}</b></div><div class="fact"><small>Walking</small><b>${p.walk}</b></div><div class="fact"><small>Cost</small><b>${p.cost}</b></div></div><div class="callout"><h3>Best approach</h3><p>${p.tip}</p></div><div class="callout"><h3>Accessibility note</h3><p>${p.access}</p></div><div class="actions"><a href="${p.maps}" target="_blank" rel="noopener">Directions</a><a href="${p.official}" target="_blank" rel="noopener">Official website</a><a href="${p.trip}" target="_blank" rel="noopener">TripAdvisor</a></div></div>`;$('#placeDialog').showModal()}
$('#closeDialog').onclick=()=>$('#placeDialog').close();$('#placeDialog').onclick=e=>{if(e.target===$('#placeDialog'))$('#placeDialog').close()};
function go(screen){$$('.screen').forEach(s=>s.classList.toggle('active',s.id===screen));$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.screen===screen));scrollTo({top:0,behavior:'smooth'})}
$$('.nav').forEach(n=>n.onclick=()=>go(n.dataset.screen));$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
$('#search').oninput=renderPlaces;$$('.chip').forEach(c=>c.onclick=()=>{$$('.chip').forEach(x=>x.classList.remove('active'));c.classList.add('active');activeFilter=c.dataset.filter;renderPlaces()});
$$('.quick').forEach(q=>q.onclick=()=>{go('explore');let p=q.dataset.preset;activeFilter=p==='spendy'?'boat':p;$$('.chip').forEach(x=>x.classList.toggle('active',x.dataset.filter===activeFilter));renderPlaces()});
$('#suggestBtn').onclick=()=>{let e=$('#energy').value,t=$('#theme').value;let list=places.filter(p=>(e==='any'||p.energy===e)&&(t==='any'||p.tags.includes(t)));list.sort(()=>Math.random()-.5);$('#suggestions').innerHTML=list.slice(0,4).map(mini).join('')||'<p>No exact match. Try “Any” for one option.</p>';bindCards()};
let deferred;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{if(deferred){deferred.prompt();await deferred.userChoice;deferred=null;$('#installBtn').hidden=true}};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));

function restaurantInitials(name){return name.split(/\s+/).filter(Boolean).slice(0,2).map(w=>w[0]).join('').toUpperCase()}
function restaurantIllustration(r){
  const icons={nearby:'⌂',village:'◌',seaside:'≈',family:'☺',special:'✦',quick:'☕',mountain:'△',daytrip:'◇'};
  return `<div class="restaurant-banner restaurant-illustration ${r.category}"><div class="restaurant-scene"><span class="scene-icon">${icons[r.category]||'✦'}</span><span class="scene-line"></span><span class="scene-dot"></span></div><span class="restaurant-initials">${restaurantInitials(r.name)}</span><span class="restaurant-price">${r.price}</span></div>`
}
function restaurantCard(r,compact=false){return `<article class="restaurant-card ${compact?'compact':''}" data-restaurant-open="${r.id}">${restaurantIllustration(r)}<button class="save ${savedRestaurants.has(r.id)?'saved':''}" data-restaurant-save="${r.id}" aria-label="Save ${r.name}">${savedRestaurants.has(r.id)?'♥':'♡'}</button><div class="body"><p class="eyebrow">${r.area}</p><h3>${r.name}</h3><div class="meta"><span>${r.drive}</span><span>${r.price}</span></div><p>${r.summary}</p><div class="restaurant-best"><b>Best for:</b> ${r.best}</div></div></article>`}
let restaurantFilter='all';
function renderRestaurants(){if(!window.RESTAURANTS||!$('#restaurantGrid'))return;let q=$('#restaurantSearch').value.toLowerCase();let list=window.RESTAURANTS.filter(r=>{let blob=(r.name+' '+r.area+' '+r.summary+' '+r.best+' '+r.tags.join(' ')).toLowerCase();return(!q||blob.includes(q))&&(restaurantFilter==='all'||r.tags.includes(restaurantFilter)||r.category===restaurantFilter)});$('#restaurantGrid').innerHTML=list.map(r=>restaurantCard(r)).join('')||'<div class="empty visible"><h3>No matches</h3><p>Try another area or dining style.</p></div>';bindRestaurants()}
function renderSavedRestaurants(){if(!window.RESTAURANTS||!$('#savedRestaurantsGroup'))return;let list=window.RESTAURANTS.filter(r=>savedRestaurants.has(r.id));$('#savedRestaurantsGrid').innerHTML=list.map(r=>restaurantCard(r)).join('');$('#savedRestaurantsGroup').style.display=list.length?'block':'none';if($('#emptySaved'))$('#emptySaved').style.display=(saved.size||list.length)?'none':'block';bindRestaurants()}
function bindRestaurants(){$$('[data-restaurant-open]').forEach(el=>el.onclick=e=>{if(e.target.closest('[data-restaurant-save]'))return;openRestaurant(el.dataset.restaurantOpen)});$$('[data-restaurant-save]').forEach(b=>b.onclick=e=>{e.stopPropagation();savedRestaurants.has(b.dataset.restaurantSave)?savedRestaurants.delete(b.dataset.restaurantSave):savedRestaurants.add(b.dataset.restaurantSave);saveRestaurantState();renderRestaurants();renderRestaurantHome();renderSavedRestaurants()})}
function openRestaurant(id){let r=window.RESTAURANTS.find(x=>x.id===id);$('#dialogContent').innerHTML=`${restaurantIllustration(r)}<div class="detail"><p class="eyebrow">${r.area}</p><h2>${r.name}</h2><p>${r.summary}</p><div class="facts"><div class="fact"><small>Drive</small><b>${r.drive}</b></div><div class="fact"><small>Price</small><b>${r.price}</b></div><div class="fact"><small>Style</small><b>${r.category}</b></div></div><div class="callout"><h3>What to order</h3><p>${r.best}</p></div><div class="callout"><h3>Booking advice</h3><p>${r.booking}</p></div><div class="callout"><h3>Accessibility note</h3><p>${r.access}</p></div><div class="verified">Recommendations are curated, but opening days, menus and ownership can change. Check before travelling.</div><div class="actions"><a href="${r.maps}" target="_blank" rel="noopener">Directions</a><a href="${r.website}" target="_blank" rel="noopener">Website / search</a><a href="${r.trip}" target="_blank" rel="noopener">TripAdvisor</a></div></div>`;$('#placeDialog').showModal()}
function renderRestaurantHome(){if(!window.RESTAURANTS||!$('#restaurantPicks'))return;let ids=['cretan-corner','pandesia','tamam','thalassino-ageri'];$('#restaurantPicks').innerHTML=ids.map(id=>restaurantCard(window.RESTAURANTS.find(r=>r.id===id),true)).join('');bindRestaurants()}
function buildRestaurantUI(){
  const css=document.createElement('link');css.rel='stylesheet';css.href='restaurants.css';document.head.appendChild(css);
  const homeSection=document.createElement('section');homeSection.className='section restaurant-home-section';homeSection.innerHTML='<div class="section-head"><div><p class="eyebrow">Where to eat</p><h2>Restaurant picks</h2></div><button class="text-btn" data-go="restaurants">See all</button></div><p class="restaurant-note">A mix of nearby tavernas, family-friendly favourites and memorable Chania dinners.</p><div id="restaurantPicks" class="card-row restaurant-row"></div>';$('#home').appendChild(homeSection);
  const restaurantScreen=document.createElement('section');restaurantScreen.id='restaurants';restaurantScreen.className='screen';restaurantScreen.innerHTML='<div class="food-hero"><div><p class="eyebrow">Curated food guide</p><h2>Restaurants worth planning around</h2><p>Nearby ease, Cretan classics, family favourites and special evenings.</p></div></div><div class="restaurant-intro"><p>August is busy. For the most popular restaurants, book ahead and ask about parking, steps and the easiest table when reserving.</p></div><div class="sticky-tools"><input id="restaurantSearch" type="search" placeholder="Search restaurants, areas or food…"><div class="chips restaurant-chips"><button class="chip active" data-rfilter="all">All</button><button class="chip" data-rfilter="nearby">Near villa</button><button class="chip" data-rfilter="family">Family</button><button class="chip" data-rfilter="traditional">Traditional</button><button class="chip" data-rfilter="seafood">Seafood</button><button class="chip" data-rfilter="chania">Chania</button><button class="chip" data-rfilter="special">Special evening</button></div></div><div id="restaurantGrid" class="place-grid restaurant-grid"></div>';
  $('main').insertBefore(restaurantScreen,$('#saved'));
  const nav=document.createElement('button');nav.className='nav';nav.dataset.screen='restaurants';nav.innerHTML='<span>♨</span>Eat';$('.bottom-nav').insertBefore(nav,$('.bottom-nav [data-screen="saved"]'));
  const savedGroup=document.createElement('div');savedGroup.id='savedRestaurantsGroup';savedGroup.className='saved-group';savedGroup.style.display='none';savedGroup.innerHTML='<p class="eyebrow">Dining shortlist</p><h3>Saved restaurants</h3><div id="savedRestaurantsGrid" class="place-grid"></div>';$('#savedGrid').after(savedGroup);
  nav.onclick=()=>go('restaurants');homeSection.querySelector('[data-go]').onclick=()=>go('restaurants');$('#restaurantSearch').oninput=renderRestaurants;$$('[data-rfilter]').forEach(c=>c.onclick=()=>{$$('[data-rfilter]').forEach(x=>x.classList.remove('active'));c.classList.add('active');restaurantFilter=c.dataset.rfilter;renderRestaurants()});
  renderRestaurantHome();renderRestaurants();renderSavedRestaurants();
}
function loadRestaurants(){let script=document.createElement('script');script.src='restaurants.js';script.onload=buildRestaurantUI;document.body.appendChild(script)}
renderAll();loadRestaurants();
