window.WEEK_GUIDE = [
  {date:'16',day:'Sunday',title:'Arrival and settle in',badge:'Keep it gentle',plan:'Collect the car, reach the villa, unpack and use the pool. If energy allows, take a very short drive to Kalyves for provisions or an easy waterfront meal.',avoid:'Do not schedule a major attraction after the overnight ferry and transfer. Save Ancient Aptera for a fresh morning.',market:null,links:[['Nearby food','restaurants'],['Kalyves','kalyves']]},
  {date:'17',day:'Monday',title:'Ancient Aptera morning',badge:'Best nearby start',plan:'Visit Ancient Aptera at opening while it is cooler, then return to the villa for lunch and the pool. It is close enough to abandon easily if the heat or energy level is wrong.',avoid:'Avoid leaving this until midday because the site is exposed. Tuesday is its regular closed day.',market:'Chania Monday market operates at the Markopoulou Camp site. It is optional rather than worth reshaping this easy first full day around.',links:[['Open Aptera','aptera'],['Monday market map','https://www.google.com/maps/search/?api=1&query=Markopoulou+Camp+Chania+market']]},
  {date:'18',day:'Tuesday',title:'Scenic drive or village day',badge:'Closure-aware',plan:'Choose Theriso Gorge for scenery with very little walking, or combine Vamos and Gavalochori with a relaxed lunch.',avoid:'Do not plan Ancient Aptera or the Archaeological Museum of Chania today. Both currently list Tuesday as their closed day.',market:null,links:[['Theriso','theriso'],['Vamos & Gavalochori','vamos']]},
  {date:'19',day:'Wednesday',title:'Chania market and Old Town',badge:'Market morning',plan:'Start with Chania’s Wednesday market at the VIOCHYM site, then continue to a short, flexible Old Town and harbour visit. Use cafés as planned rest stops rather than attempting a long walking route.',avoid:'Chania parking is harder around market time. Arrive early, use a larger car park or consider a taxi for the city portion.',market:'The Municipality of Chania lists the Wednesday market at the VIOCHYM site. Market arrangements can move, so recheck shortly before the holiday.',links:[['Market map','https://www.google.com/maps/search/?api=1&query=VIOCHYM+Chania'],['Chania Old Town','chania']]},
  {date:'20',day:'Thursday',title:'Eponine’s birthday choice',badge:'Birthday',birthday:true,plan:'Make this a flexible celebration day. One strong option is the Archaeological Museum of Chania in the morning, then pool time and a booked special dinner. Another is Lake Kournas with a pedal boat if she prefers a family activity.',avoid:'Do not overfill the day. August heat, city walking and a late dinner together can turn a celebration into an endurance test.',market:'Chania’s Thursday market now operates in the former AVEA site. Visit only if Eponine would enjoy it, rather than making the birthday revolve around errands.',links:[['Museum','museum'],['Lake Kournas','kournas'],['Birthday dinner','restaurants']]},
  {date:'21',day:'Friday',title:'Choose the spectacular day',badge:'Weather dependent',plan:'Use Friday for the trip that most depends on favourable conditions: Balos, Falassarna, Elafonissi or a boat outing. Check wind, heat and sea conditions the evening before.',avoid:'Avoid committing to a long western drive if strong wind, extreme heat or poor sleep makes it a bad fit. Keep Theriso or Rethymno as lower-pressure alternatives.',market:null,links:[['Spectacular places','explore']]},
  {date:'22',day:'Saturday',title:'Rethymno and market option',badge:'Good final full day',plan:'Visit Rethymno early, with the Saturday market as an optional first stop, then explore only a compact section of the Old Town. Alternatively, keep the final day local with Kalyves, Marathi or a village lunch.',avoid:'Rethymno and the north-coast road are busy on summer Saturdays. Leave early and do not rely on finding close Old Town parking.',market:'Rethymno Municipality lists a Saturday market in the car park between the stadium and bus station, generally from early morning until around 14:00–15:00.',links:[['Rethymno','rethymno'],['Saturday market map','https://www.google.com/maps/search/?api=1&query=Rethymno+stadium+bus+station+market']]},
  {date:'23',day:'Sunday',title:'Departure day',badge:'No pressure',plan:'Pack, check out and keep any final stop close to the route. A short breakfast or waterfront stop is safer than trying to squeeze in a major attraction before travelling.',avoid:'Do not leave luggage visible in the car during a final stop, and allow significantly more time than the map estimate for summer traffic and returning the hire car.',market:null,links:[['Nearby restaurants','restaurants']]}
];

(function(){
 const css=document.createElement('link');css.rel='stylesheet';css.href='week-guide.css';document.head.appendChild(css);
 const screen=document.createElement('section');screen.id='week';screen.className='screen';
 screen.innerHTML=`<div class="week-hero"><div><p class="eyebrow">16–23 August 2026</p><h2>Your week, planned intelligently</h2><p>Use market days and regular closures to choose the right outing, while keeping every day flexible around heat and energy.</p></div></div>
 <div class="week-alert"><b>Important:</b> market locations and summer opening hours can change. This guide uses the latest published information, but check linked official pages again shortly before travelling.</div>
 <div class="planning-rules"><div class="rule-card"><h3>Tuesday rule</h3><p>Keep Tuesday for drives, villages or water. Ancient Aptera and the Archaeological Museum currently list Tuesday closures.</p></div><div class="rule-card"><h3>Market rule</h3><p>Go early. Markets are cooler, less crowded and easier to combine with a short city visit before lunch.</p></div><div class="rule-card"><h3>Heat rule</h3><p>Outdoor archaeology before 10:30. Museums, lunch, scenic drives and the villa pool for the hottest hours.</p></div></div>
 <div id="weekGrid" class="week-grid"></div>
 <div class="source-note">Checked against current official information from the <a href="https://www.chania.gr/enimerosi/nea/arxeia-dt/archeio-dt-2026/sto-oikopedo-tis-proin-avea-i-laiki-agora-tis-pebtis/" target="_blank" rel="noopener">Municipality of Chania</a>, <a href="https://ancientaptera.gr/en/contact_us/" target="_blank" rel="noopener">Ancient Aptera</a>, the <a href="https://amch.gr/en/" target="_blank" rel="noopener">Archaeological Museum of Chania</a> and the <a href="https://www.rethymno.gr/en/city/dieta-cretese/mercati-all-aperto.html" target="_blank" rel="noopener">Municipality of Rethymno</a>.</div>`;
 document.querySelector('main').insertBefore(screen,document.querySelector('#restaurants'));
 const nav=document.createElement('button');nav.className='nav';nav.dataset.screen='week';nav.innerHTML='<span>▦</span>Week';document.querySelector('.bottom-nav').insertBefore(nav,document.querySelector('.bottom-nav [data-screen="restaurants"]'));nav.onclick=()=>go('week');
 function action(link){const [label,target]=link;if(target==='restaurants'||target==='explore'){return `<button data-week-go="${target}">${label}</button>`}const place=places.find(p=>p.id===target);if(place)return `<button data-week-place="${target}">${label}</button>`;return `<a class="secondary" href="${target}" target="_blank" rel="noopener">${label}</a>`}
 document.querySelector('#weekGrid').innerHTML=window.WEEK_GUIDE.map(d=>`<article class="day-card ${d.birthday?'birthday':''}"><div class="day-head"><div class="day-date"><b>${d.date}</b><span>Aug</span></div><div class="day-title"><h3>${d.day}: ${d.title}</h3><p>${d.birthday?'Eponine’s 9th birthday':'Flexible family plan'}</p></div><span class="day-badge">${d.badge}</span></div><div class="day-body"><div class="day-columns"><div class="day-box"><h4>Good plan</h4><p>${d.plan}</p></div><div class="day-box avoid"><h4>Watch out for</h4><p>${d.avoid}</p></div></div>${d.market?`<div class="market-row"><span class="market-icon">▤</span><div><b>Market note</b><span>${d.market}</span></div></div>`:''}<div class="day-actions">${d.links.map(action).join('')}</div></div></article>`).join('');
 document.querySelectorAll('[data-week-go]').forEach(b=>b.onclick=()=>go(b.dataset.weekGo));document.querySelectorAll('[data-week-place]').forEach(b=>b.onclick=()=>openPlace(b.dataset.weekPlace));
 const home=document.createElement('section');home.className='section';home.innerHTML='<div class="section-head"><div><p class="eyebrow">Plan around the island</p><h2>Day-by-day guide</h2></div><button class="text-btn">Open week</button></div><div class="note"><h3>Tuesday is the key closure day</h3><p>Use Tuesday for a scenic drive or village lunch, then place archaeology and the Chania museum on other mornings.</p></div>';document.querySelector('#home').appendChild(home);home.querySelector('button').onclick=()=>go('week');
})();
